### ISSUE TITLE
bug: Uses default credentials instead of provider

### ISSUE THREAD

**Issue by bminer** [medikoo/serverless-plugin-vpc-eni-cleanup#1]
Should probably obey `provider: profile` in `serverless.yml` file.

**Comment by medikoo** [comment]
@bminer thanks for reporting, indeed `provider: profile` should be respected. I marked it with `help wanted` (PR's welcome)

**Comment by bminer** [comment]
Thanks, @medikoo. I probably won't be much help on this one. I don't know how this works, and I'm definitely not a AWS Lambda expert (not yet anyway).
