### ISSUE TITLE
Prevents node from exiting if removal fails

### ISSUE THREAD

**Issue by perrin4869** [medikoo/serverless-plugin-vpc-eni-cleanup#10]
For example, if the CF stack didn't exist. This is because https://github.com/medikoo/serverless-plugin-vpc-eni-cleanup/blob/69afe39d3e73c74b1070305507362e490a41fc62/index.js#L16 never gets triggered.
Is there a hook to listen to in case `remove` fails?

**Comment by medikoo** [comment]
@perrin4869 that's a good point.

I think it can be solved by adding `error` hook with same logic. Such hook was introduced with v2.58 of Framework so it's possible to run logic if any of the hooks logic crashes

PR's welcome!

**Comment by perrin4869** [comment]
Done!
