### ISSUE TITLE
VPC ENI Cleanup: Error: Missing credentials in config

### ISSUE THREAD

**Issue by joonhwa** [medikoo/serverless-plugin-vpc-eni-cleanup#4]
I am getting this error when running the plugin. Any idea what is wrong? Thanks.

VPC ENI Cleanup: Error: Missing credentials in config
{ Error: connect EHOSTUNREACH 169.254.169.254:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
  message: 'Missing credentials in config',
  errno: 'EHOSTUNREACH',
  code: 'CredentialsError',
  syscall: 'connect',
  address: '169.254.169.254',
  port: 80,
  time: 2019-03-06T01:26:18.575Z,
  originalError: 
   { message: 'Could not load credentials from any providers',
     errno: 'EHOSTUNREACH',
     code: 'CredentialsError',
     syscall: 'connect',
     address: '169.254.169.254',
     port: 80,
     time: 2019-03-06T01:26:18.575Z,
     originalError: 
      { message: 'Missing credentials in config',
        errno: 'EHOSTUNREACH',
        code: 'CredentialsError',
        syscall: 'connect',
        address: '169.254.169.254',
        port: 80,
        time: 2019-03-06T01:26:18.574Z,
        originalError: [Object] } } }

**Comment by medikoo** [comment]
If it's not in general about AWS credentials not being provided to SLS, then it's possibly related to: https://github.com/medikoo/serverless-plugin-vpc-eni-cleanup/issues/1  (?)

**Comment by joonhwa** [comment]
It used to be working coupe of months back when i started using it. Not sure why it is broken now. Is there any workaround to get this working with the current version of the code?

**Comment by medikoo** [comment]
> Is there any workaround to get this working with the current version of the code?

There haven't been any changes to this plugin for 7 months.

Maybe it's something that changed in SLS framework? Have you tried to run it with older version?

**Comment by joonhwa** [comment]
hmm.. let me give it a try and feedback later on

**Comment by jonathandeclan** [comment]
> > Is there any workaround to get this working with the current version of the code?
> 
> There haven't been any changes to this plugin for 7 months.
> 
> Maybe it's something that changed in SLS framework? Have you tried to run it with older version?

What's the SLS version that is supported by this plugin?

**Comment by medikoo** [comment]
>  What's the SLS version that is supported by this plugin?

https://github.com/medikoo/serverless-plugin-vpc-eni-cleanup/blob/26d1e6f6a151a96f736ce237e18a01469d37e163/package.json#L35

**Comment by jonathandeclan** [comment]
> > What's the SLS version that is supported by this plugin?
> 
> https://github.com/medikoo/serverless-plugin-vpc-eni-cleanup/blob/26d1e6f6a151a96f736ce237e18a01469d37e163/package.json#L35

Does this mean 1.0 or 1.x ? if it's 1.x (which serverless has been the past 3 years) , what is the older version you are referring to? We have using 1.41.1 and we have to wait past an hour for the eni to be removed.

**Comment by medikoo** [comment]
> Does this mean 1.0 or 1.x

It's semver range, see: https://devhints.io/semver

It's equal to `1.x`, `1.x.x`, `^1.0.0` etc
