### ISSUE TITLE
Support Serverless Framework >= 2.0.0 

### ISSUE THREAD

**Issue by joker-8989** [medikoo/serverless-plugin-vpc-eni-cleanup#6]
With the release of serverless version 2, this plugin now raises the following warning.

```
warning " > serverless-plugin-vpc-eni-cleanup@1.0.0" has incorrect peer dependency "serverless@1".
```

This plugin should update this dependency if there are no significant issues with Serverless 2 usage.
Currently this plugin works with version 2 of my environment.

**Comment by medikoo** [comment]
@joker-8989 great thanks for pointing. Released v1.0.1 which declares support for v2
